import { NextRequest } from 'next/server';
import { withAuth, apiSuccess, apiError } from '@/lib/api-helpers';
import { getLeadById } from '@/lib/data/leads';
import {
  getResearchForLead,
  upsertResearch,
  getCallNoteForLead,
  upsertCallNote,
  getPitchesForLead,
  createPitch,
  addActivity,
  incrementStat,
  getSettings,
  addLog,
} from '@/lib/data';
import { generateResearch, generateCallNote, generatePitch } from '@/lib/ai';

// POST /api/leads/[id]/generate
// body: { action: 'research' | 'call_note' | 'pitch', serviceId?, language? }
export const POST = withAuth(async ({ session, req }, context?: { params?: Promise<{ id: string }> }) => {
  const { id } = await (context?.params ?? Promise.resolve({ id: '' }));
  const body = await req.json();
  const { action, serviceId, language = 'english' } = body;

  // Permission check
  const lead = await getLeadById(id);
  if (!lead) return apiError('Lead not found', 404);

  if (
    session.role !== 'admin' &&
    !session.permissions.can_view_all_leads &&
    lead.assigned_to !== session.id &&
    lead.added_by !== session.id
  ) {
    return apiError('Forbidden', 403);
  }

  const settings = await getSettings();

  try {
    if (action === 'research') {
      const research = await generateResearch(lead);
      await upsertResearch(research);
      await addActivity({
        lead_id: id,
        user_id: session.id,
        type: 'ai_research',
        content: `Research generated by ${session.username}`,
      });
      const today = new Date().toISOString().slice(0, 10);
      await incrementStat(today, session.id, 'ai_research').catch(() => {});
      return apiSuccess(research);
    }

    if (action === 'call_note') {
      let research = await getResearchForLead(id);
      if (!research) {
        research = await generateResearch(lead);
        await upsertResearch(research);
      }
      const note = await generateCallNote(lead, research);
      await upsertCallNote({
        lead_id: id,
        call_prep_note: note.call_prep_note,
        opening_lines: note.opening_lines,
        objection_handlers: note.objection_handlers,
        created_at: new Date().toISOString(),
      });
      await addActivity({
        lead_id: id,
        user_id: session.id,
        type: 'ai_call_note',
        content: `Call note generated by ${session.username}`,
      });
      return apiSuccess(note);
    }

    if (action === 'pitch') {
      let research = await getResearchForLead(id);
      if (!research) {
        research = await generateResearch(lead);
        await upsertResearch(research);
      }

      const targetServiceId = serviceId || research.recommended_service_id;
      if (!targetServiceId) return apiError('No service specified and no recommendation available');

      const { message_text, wa_link } = await generatePitch(lead, research, targetServiceId, language);

      // Version = how many pitches exist for this lead + 1
      const existing = await getPitchesForLead(id);
      const version = String(existing.length + 1);

      const pitch = await createPitch({
        lead_id: id,
        service_id: targetServiceId,
        message_text,
        wa_link,
        version,
        generated_by: session.id,
        generated_at: new Date().toISOString(),
        edited_by: '',
      });

      await addActivity({
        lead_id: id,
        user_id: session.id,
        type: 'ai_pitch',
        content: `Pitch v${version} generated by ${session.username}`,
      });

      const today = new Date().toISOString().slice(0, 10);
      await incrementStat(today, session.id, 'pitches_generated').catch(() => {});

      return apiSuccess(pitch);
    }

    return apiError('Invalid action. Use: research, call_note, pitch');
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'AI generation failed';
    await addLog({ user: session.username, action: 'AI_ERROR', details: msg });
    return apiError(msg, 500);
  }
});
